application: dollyn66
version: 0-1-201202042109
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /notes/.*
  script: note.py
  login: required
  secure: always

- url: /cates/.*
  script: cates.py
  
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico